### ISSUE TITLE
请教一下printable里面的pdf文件是如何生成的

### ISSUE THREAD

**Issue by AIboy996** [wangyingsm/Python-Data-Science-Handbook#3]
感觉这些pdf制作的很精美，想学习一下！我自己直接使用浏览器打印会有分页问题。

如果此类问题不适合在issues中提出，请忽略qwq

**Comment by wangyingsm** [comment]
这是Jupyter Notebook的插件生成的。

![image](https://user-images.githubusercontent.com/17978916/167076838-ccd05fd7-05ff-4ea4-a73c-7991596cd377.png)

**Comment by wangyingsm** [comment]
Jupyter notebook的插件啊。已在issue #3做出回答，如无其他问题，issue会被关闭。谢谢。




王滢
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangyingsm/Python-Data-Science-Handbook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 上午10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wangyingsm/Python-Data-Science-Handbook] 请教一下printable里面的pdf文件是如何生成的 (Issue #3)





 
感觉这些pdf制作的很精美，想学习一下！我自己直接使用浏览器打印会有分页问题。
 
如果此类问题不适合在issues中提出，请忽略qwq
